apiVersion: v1
kind: Service
metadata:
  name: cloud
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    com.docker.project: cloud
  type: LoadBalancer
status:
  loadBalancer: {}
 